<?php
/**
 * Main class for Add To Cart Redirect
 *
 * @package     cashier/includes/
 *  author      StoreApps
 * @since       1.3.0
 * @version     1.1.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

if ( ! class_exists( 'SA_Add_To_Cart_Redirect' ) ) {

	/**
	 *  Add To Cart Redirect Class.
	 *
	 * @return object of SA_Add_To_Cart_Redirect having all functionality of Add To Cart Redirect
	 */
	class SA_Add_To_Cart_Redirect {

		/**
		 * Variable to hold instance of Add To Cart Redirect
		 *
		 * @var $instance
		 */
		private static $instance = null;

		/**
		 * Get single instance of Add To Cart Redirect.
		 *
		 * @return SA_Add_To_Cart_Redirect Singleton object of SA_Add_To_Cart_Redirect
		 */
		public static function get_instance() {

			// Check if instance is already exists.
			if ( is_null( self::$instance ) ) {
				self::$instance = new self();
			}

			return self::$instance;
		}

		/**
		 * Cloning is forbidden.
		 *
		 * @since 1.0.0
		 */
		private function __clone() {
			wc_doing_it_wrong( __FUNCTION__, __( 'Cheatin&#8217; huh?', 'cashier' ), '1.0.0' );
		}

		/**
		 * Unserializing instances of this class is forbidden.
		 *
		 * @since 1.0.0
		 */
		public function __wakeup() {
			wc_doing_it_wrong( __FUNCTION__, __( 'Cheatin&#8217; huh?', 'cashier' ), '1.0.0' );
		}

		/**
		 * Constructor
		 */
		private function __construct() {
			if ( ! defined( 'SA_ACR_PLUGIN_DIRPATH' ) ) {
				define( 'SA_ACR_PLUGIN_DIRPATH', dirname( __FILE__ ) );
			}
			// show selectwoo.
			add_action( 'woocommerce_product_after_variable_attributes', array( $this, 'show_selectwoo_for_variation' ), 10, 3 );
			add_action( 'woocommerce_product_options_general_product_data', array( $this, 'show_selectwoo_for_product' ) );
			add_action( 'admin_footer', array( $this, 'styles_and_scripts' ) );
			// search post json call.
			add_action( 'wp_ajax_cfwc_json_search_posts', array( $this, 'cfwc_json_search_posts' ), 1, 2 );
			// handle redirect.
			add_filter( 'woocommerce_add_to_cart_redirect', array( $this, 'cfwc_redirect_after_cart' ), 10, 2 );

			// save options.
			add_action( 'woocommerce_save_product_variation', array( $this, 'save_variation_redirect_option' ), 10, 2 );
			add_action( 'woocommerce_process_product_meta', array( $this, 'save_product_redirect_option' ), 10, 2 );

		}

		/**
		 * Function to handle WC compatibility related function call from appropriate class
		 *
		 * @param string $function_name Function to call.
		 * @param array  $arguments Array of arguments passed while calling $function_name.
		 * @return mixed Result of function call.
		 */
		public function __call( $function_name, $arguments = array() ) {

			if ( ! is_callable( 'SA_WC_Compatibility_4_1', $function_name ) ) {
				return;
			}

			if ( ! empty( $arguments ) ) {
				return call_user_func_array( 'SA_WC_Compatibility_4_1::' . $function_name, $arguments );
			} else {
				return call_user_func( 'SA_WC_Compatibility_4_1::' . $function_name );
			}

		}

		/**
		 * Function to log messages generated by add to cart redirect module
		 *
		 * @param  string $level   Message type. Valid values: debug, info, notice, warning, error, critical, alert, emergency.
		 * @param  string $message The message to log.
		 */
		public function log( $level = 'notice', $message = '' ) {

			if ( empty( $message ) ) {
				return;
			}

			if ( function_exists( 'wc_get_logger' ) ) {
				$logger  = wc_get_logger();
				$context = array( 'source' => 'cashier' );
				$logger->log( $level, $message, $context );
			} else {
				include_once plugin_dir_path( WC_PLUGIN_FILE ) . 'includes/class-wc-logger.php';
				$logger = new WC_Logger();
				$logger->add( 'cashier', $message );
			}

		}

		/**
		 * Function to fetch plugin's data
		 */
		public function get_plugin_data() {
			return get_plugin_data( SA_CFW_PLUGIN_FILE );
		}

		/**
		 * Register select2 in variation option
		 *
		 * @param int     $loop Variation loop count.
		 * @param array   $variation_data Variation data.
		 * @param WP_Post $variation Post object.
		 */
		public function show_selectwoo_for_variation( $loop = null, $variation_data = array(), $variation = null ) {
			$variation_id                        = $variation->ID;
			$woocommerce_enable_ajax_add_to_cart = get_option( 'woocommerce_enable_ajax_add_to_cart', false );
			?>
			<div class="options_group cfw-field">
				<p class="form-field post_<?php echo esc_attr( $variation_id ); ?> form-row form-row-full">
					<label for="cfw_search_post"><?php echo esc_html__( 'Add to cart redirect', 'cashier' ); ?></label>
					<?php $this->render_selectwoo_for_posts( $variation_id, 'yes' ); ?>
				</p>
				<p class="form-field form-row form-row-full">
					<?php $this->ajax_on_archive_notice(); ?>
				</p>
			</div>
			<?php
		}

		/**
		 * Register select2 in product
		 */
		public function show_selectwoo_for_product() {
			global $post;
			$product_id = $post->ID;
			?>
			<div class="options_group cfw-field">
				<p class="form-field post_<?php echo esc_attr( $product_id ); ?>">
					<label for="cfw_search_post"><?php echo esc_html__( 'Add to cart redirect', 'cashier' ); ?></label>
					<?php $this->render_selectwoo_for_posts( $product_id ); ?>
				</p>
				<p class="form-field">
					<?php $this->ajax_on_archive_notice(); ?>
				</p>
			</div>
			<?php
		}

		/**
		 * Display notice about AJAX on archive pages
		 */
		public function ajax_on_archive_notice() {
			?>
			<span class="dashicons dashicons-warning"></span>
			<span><?php esc_attr_e( 'Redirect will not work for AJAX add to cart buttons on archives', 'cashier' ); ?></span>
			<?php
		}

		/**
		 * Register select2 in product
		 *
		 * @param int    $object_id selected post.
		 * @param string $is_variation Whether it's for variation or not.
		 */
		public function render_selectwoo_for_posts( $object_id = 0, $is_variation = 'no' ) {
			$selected_post_id    = get_post_meta( $object_id, 'cfw_redirect_post', true );
			$selected_post_title = ( ! empty( $selected_post_id ) ) ? get_the_title( $selected_post_id ) : '';
			?>
			<select id="cfwc_select_posts_<?php echo esc_attr( $object_id ); ?>" name="cfwc_redirect_<?php echo esc_attr( $object_id ); ?>" style="width: <?php echo esc_attr( ( 'yes' === $is_variation ) ? '100% !important' : '50%' ); ?>;" class="wc-cfw-posts-search" data-placeholder="<?php esc_attr_e( 'Search posts', 'affiliate-for-woocommerce' ); ?>" data-allow_clear="true" data-action="cfwc_json_search_posts">
				<?php if ( ! empty( $selected_post_id ) ) { ?>
					<option selected="selected" value="<?php echo esc_attr( $selected_post_id ); ?>"><?php echo esc_attr( $selected_post_title ); ?></option>
				<?php } ?>
			</select>
			<?php
		}

		/**
		 * Styles and scripts
		 */
		public function styles_and_scripts() {
			global $post;

			if ( ! empty( $post->post_type ) && 'product' === $post->post_type && ! empty( $post->ID ) ) {
				if ( ! wp_script_is( 'jquery' ) ) {
					wp_enqueue_script( 'jquery' );
				}
				?>
				<style type="text/css">
					.cfwc-post-meta{
						float: right;
						text-transform: capitalize;
					}
					.cfw-field .form-field .dashicons.dashicons-warning {
						font-size: 1.4em;
						vertical-align: bottom;
					}
				</style>
				<script type="text/javascript">
					jQuery(function(){
						if ( typeof getEnhancedSelectFormatString == "undefined" ) {
							function getEnhancedSelectFormatString() {
								return {
									'language': {
										errorLoading: function() {
											// Workaround for https://github.com/select2/select2/issues/4355 instead of i18n_ajax_error.
											return wc_enhanced_select_params.i18n_searching;
										},
										inputTooLong: function( args ) {
											var overChars = args.input.length - args.maximum;

											if ( 1 === overChars ) {
												return wc_enhanced_select_params.i18n_input_too_long_1;
											}

											return wc_enhanced_select_params.i18n_input_too_long_n.replace( '%qty%', overChars );
										},
										inputTooShort: function( args ) {
											var remainingChars = args.minimum - args.input.length;

											if ( 1 === remainingChars ) {
												return wc_enhanced_select_params.i18n_input_too_short_1;
											}

											return wc_enhanced_select_params.i18n_input_too_short_n.replace( '%qty%', remainingChars );
										},
										loadingMore: function() {
											return wc_enhanced_select_params.i18n_load_more;
										},
										maximumSelected: function( args ) {
											if ( args.maximum === 1 ) {
												return wc_enhanced_select_params.i18n_selection_too_long_1;
											}

											return wc_enhanced_select_params.i18n_selection_too_long_n.replace( '%qty%', args.maximum );
										},
										noResults: function() {
											return wc_enhanced_select_params.i18n_no_matches;
										},
										searching: function() {
											return wc_enhanced_select_params.i18n_searching;
										}
									}
								};
							}
						}
						var select2_args = {
							allowClear:  true,
							placeholder: jQuery( this ).data( 'placeholder' ),
							minimumInputLength: 3,
							escapeMarkup: function( m ) {
								return m;
							},
							ajax: {
								url:         ajaxurl,
								dataType:    'json',
								delay:       1000,
								data:        function( params ) {
									return {
										term:     params.term,
										action:   'cfwc_json_search_posts',
										security: '<?php echo esc_attr( wp_create_nonce( 'cfw-search-all-posts' ) ); ?>',
										exclude:  jQuery( this ).data( 'exclude' )
									};
								},
								processResults: function( data ) {
									var terms = [];
									if ( data ) {
										jQuery.each( data, function( res ) {
											terms.push({
												id: res,
												title: data[res].title,
												text: '<span>' + data[res].title + '</span><span class="cfwc-post-meta">' + data[res].type + '</span>'
											});
										});
									}
									return {
										results: terms
									};
								},
								cache: true
							},
							templateSelection: function(data) {
								return data.title || data.text;
							}
						};

						select2_args = jQuery.extend( select2_args, getEnhancedSelectFormatString() );

						function bind_cfw_posts_search() {
							jQuery('select.wc-cfw-posts-search').filter( ':not(.cfw-bind)' ).each( function() {
								jQuery( this ).selectWoo( select2_args ).addClass( 'cfw-bind' );
							});
						}

						bind_cfw_posts_search();

						jQuery(document.body).on('woocommerce_variations_loaded woocommerce_variations_added', function(){
							bind_cfw_posts_search();
						});

					});
				</script>
				<?php
			}
		}

		/**
		 * Search for attribute values and return json
		 *
		 * @param string $x string.
		 * @param string $attribute string.
		 * @return void
		 */
		public function cfwc_json_search_posts( $x = '', $attribute = '' ) {

			check_ajax_referer( 'cfw-search-all-posts', 'security' );

			$term = ( ! empty( $_GET['term'] ) ) ? (string) urldecode( stripslashes( wp_strip_all_tags( $_GET ['term'] ) ) ) : ''; // phpcs:ignore
			if ( empty( $term ) ) {
				die();
			}

			$posts = array();

			$all_posts = get_posts(
				array(
					'posts_per_page' => -1,
					'numberposts'    => -1,
					'fields'         => 'ids',
					'post_status'    => 'publish',
					'name__like'     => $term,
					'post_type'      => 'any',
				)
			);

			if ( $all_posts ) {
				foreach ( $all_posts as $post_id ) {
					$posts[ $post_id ]['title'] = get_the_title( $post_id );
					$posts[ $post_id ]['type']  = get_post_type( $post_id );
				}
			}
			echo wp_json_encode( $posts );
			die();

		}

		/**
		 * Function for saving variation redirection
		 *
		 * @param  integer $variation_id Variation ID.
		 * @param  integer $i Loop ID.
		 */
		public function save_variation_redirect_option( $variation_id, $i ) {

			// Check the nonce.
			if ( empty( $_POST['security'] ) || ! wp_verify_nonce( wc_clean( wp_unslash( $_POST['security'] ) ), 'save-variations' ) ) { // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
				return;
			}

			if ( empty( $variation_id ) ) {
				return;
			}

			$cfw_redirect_post_id = ( ! empty( $_POST['cfwc_redirect_' . $variation_id] ) ) ? wc_clean( wp_unslash( $_POST['cfwc_redirect_' . $variation_id] ) ) : ''; // phpcs:ignore

			if ( ! empty( $cfw_redirect_post_id ) ) {
				update_post_meta( $variation_id, 'cfw_redirect_post', $cfw_redirect_post_id );
			} else {
				delete_post_meta( $variation_id, 'cfw_redirect_post' );
			}

		}

		/**
		 * Function to save product redirection option
		 *
		 * @param int    $post_id The post id.
		 * @param object $post The post object.
		 */
		public function save_product_redirect_option( $post_id, $post ) {

			// Check the nonce.
			if ( empty( $_POST['woocommerce_meta_nonce'] ) || ! wp_verify_nonce( wc_clean( wp_unslash( $_POST['woocommerce_meta_nonce'] ) ), 'woocommerce_save_data' ) ) { // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
				return;
			}

			if ( empty( $post_id ) ) {
				return;
			}

			$cfw_redirect_post_id = ( ! empty( $_POST['cfwc_redirect_' . $post_id] ) ) ? wc_clean( wp_unslash( $_POST['cfwc_redirect_' . $post_id] ) ) : ''; // phpcs:ignore
			if ( ! empty( $cfw_redirect_post_id ) ) {
				update_post_meta( $post_id, 'cfw_redirect_post', $cfw_redirect_post_id );
			} else {
				delete_post_meta( $post_id, 'cfw_redirect_post' );
			}

		}


		/**
		 * Redirect to URL after add to cart
		 *
		 * @param string $url string.
		 * @param object $product mixed.
		 * @return $url
		 */
		public function cfwc_redirect_after_cart( $url = '', $product = null ) {
			$product_id   = ( is_object( $product ) && is_callable( array( $product, 'get_id' ) ) ) ? $product->get_id() : 0;
			$variation_id = ( ! empty( $_REQUEST['variation_id'] ) ) ? absint( wp_unslash( $_REQUEST['variation_id'] ) ) : 0;  // phpcs:ignore WordPress.Security.NonceVerification.Recommended
			if ( ! empty( $variation_id ) ) {
				$add_to_cart_option = get_post_meta( $variation_id, 'cfw_redirect_post', true );
				$product_id         = ( ! empty( $add_to_cart_option ) ) ? $variation_id : $product_id;
			}
			$add_to_cart_option = ( ! empty( $product_id ) ) ? get_post_meta( $product_id, 'cfw_redirect_post', true ) : '';
			if ( ! empty( $add_to_cart_option ) ) {
				$url = get_permalink( $add_to_cart_option );
			}
			return apply_filters(
				'cfw_add_to_cart_redirect_url',
				$url,
				array(
					'source'             => $this,
					'product_obj'        => $product,
					'add_to_cart_option' => $add_to_cart_option,
				)
			);
		}

	}

}

SA_Add_To_Cart_Redirect::get_instance();
