<?php
/**
 * Main class for Cart Notices
 *
 * @package     cashier/includes/
 *  author      StoreApps
 * @since       1.4.0
 * @version     1.2.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

if ( ! class_exists( 'SA_Cart_Notices' ) ) {

	/**
	 *  Cart Notices Class.
	 *
	 * @return object of SA_Cart_Notices having all functionality of Cart Notices
	 */
	class SA_Cart_Notices {

		/**
		 * Variable to hold instance of Cart Notices
		 *
		 * @var $instance
		 */
		private static $instance = null;

		/**
		 * Get single instance of Cart Notices.
		 *
		 * @return SA_Cart_Notices Singleton object of SA_Cart_Notices
		 */
		public static function get_instance() {
			// Check if instance is already exists.
			if ( is_null( self::$instance ) ) {
				self::$instance = new self();
			}

			return self::$instance;
		}

		/**
		 * Cloning is forbidden.
		 *
		 * @since 1.0.0
		 */
		private function __clone() {
			wc_doing_it_wrong( __FUNCTION__, __( 'Cheatin&#8217; huh?', 'cashier' ), '1.0.0' );
		}

		/**
		 * Unserializing instances of this class is forbidden.
		 *
		 * @since 1.0.0
		 */
		public function __wakeup() {
			wc_doing_it_wrong( __FUNCTION__, __( 'Cheatin&#8217; huh?', 'cashier' ), '1.0.0' );
		}

		/**
		 * Constructor
		 */
		private function __construct() {
			// add the notices to the top of the cart/checkout pages.
			add_action( 'woocommerce_before_cart_contents', array( $this, 'cart_notice' ) );
			add_action( 'woocommerce_before_checkout_form', array( $this, 'cart_notice' ) );
		}

		/**
		 * Function to handle WC compatibility related function call from appropriate class
		 *
		 * @param string $function_name Function to call.
		 * @param array  $arguments Array of arguments passed while calling $function_name.
		 * @return mixed Result of function call.
		 */
		public function __call( $function_name, $arguments = array() ) {
			if ( ! is_callable( 'SA_WC_Compatibility_4_1', $function_name ) ) {
				return;
			}

			if ( ! empty( $arguments ) ) {
				return call_user_func_array( 'SA_WC_Compatibility_4_1::' . $function_name, $arguments );
			} else {
				return call_user_func( 'SA_WC_Compatibility_4_1::' . $function_name );
			}
		}

		/**
		 * Function to log messages generated by cart notices module
		 *
		 * @param  string $level   Message type. Valid values: debug, info, notice, warning, error, critical, alert, emergency.
		 * @param  string $message The message to log.
		 */
		public function log( $level = 'notice', $message = '' ) {
			if ( empty( $message ) ) {
				return;
			}

			if ( function_exists( 'wc_get_logger' ) ) {
				$logger  = wc_get_logger();
				$context = array( 'source' => 'cashier' );
				$logger->log( $level, $message, $context );
			} else {
				include_once plugin_dir_path( WC_PLUGIN_FILE ) . 'includes/class-wc-logger.php';
				$logger = new WC_Logger();
				$logger->add( 'cashier', $message );
			}
		}

		/**
		 * Function to fetch plugin's data
		 */
		public function get_plugin_data() {
			return get_plugin_data( SA_CFW_PLUGIN_FILE );
		}

		/**
		 * Cart notice
		 *
		 * @since 1.0.0
		 */
		public function cart_notice() {
			$is_cart = ( is_callable( 'WC' ) && isset( WC()->cart ) && ! WC()->cart->is_empty() ) ? true : false;
			if ( ! $is_cart ) {
				return false;
			}

			// Get shipping total.
			$shipping_total = ( is_callable( array( WC()->cart, 'get_shipping_total' ) ) ) ? floatval( WC()->cart->get_shipping_total() ) : 0;

			$is_show_free_shipping_minimum_notice = apply_filters(
				'cfw_cn_is_show_free_shipping_minimum_notice',
				$shipping_total > 0,
				array(
					'source'         => $this,
					'shipping_total' => $shipping_total,
				)
			);

			if ( false === boolval( $is_show_free_shipping_minimum_notice ) ) {
				return false;
			}

			$tax_display_cart = get_option( 'woocommerce_tax_display_cart' );
			if ( 'incl' !== $tax_display_cart ) {
				$cart_contents_total = ( isset( WC()->cart->cart_contents_total ) ) ? WC()->cart->cart_contents_total : 0;
			} else {
				$cart_contents_total = ( isset( WC()->cart->cart_contents_total ) && isset( WC()->cart->tax_total ) ) ? WC()->cart->cart_contents_total + WC()->cart->tax_total : 0;
			}
			$cart_free_shipping_minimum = $this->get_cart_free_shipping_minimum();
			// they already meet the target amount.
			if ( is_numeric( $cart_free_shipping_minimum ) && $cart_contents_total >= $cart_free_shipping_minimum ) {
				return false;
			}

			$min_amount_required = wc_price( $cart_free_shipping_minimum - $cart_contents_total );

			/* translators: minimum ammount for shipping */
			$message       = sprintf( __( 'Add %s to your cart in order to receive free shipping!', 'cashier' ), '<strong>' . $min_amount_required . '</strong>' );
			$message       = apply_filters(
				'cfw_cn_message',
				$message,
				array(
					'source'              => $this,
					'min_amount_required' => $min_amount_required,
				)
			);
			$shop_now_text = __( 'Shop Now', 'cashier' );
			$shop_now_text = apply_filters(
				'cfw_cn_cta_text',
				$shop_now_text,
				array(
					'source'              => $this,
					'min_amount_required' => $min_amount_required,
				)
			);
			$page_id       = apply_filters(
				'cfw_cn_cta_page_id',
				wc_get_page_id( 'shop' ),
				array(
					'source'              => $this,
					'min_amount_required' => $min_amount_required,
				)
			);
			$shop_page_url = ( ! empty( $page_id ) ) ? get_permalink( $page_id ) : home_url();
			$message_html  = "<div class='woocommerce-info'>" . $message . "<a class='button' href=" . $shop_page_url . '>' . $shop_now_text . '</a></div>';
			echo wp_kses_post( $message_html );
		}

		/**
		 * Gets the free shipping minimum for the current cart and available zone.
		 *
		 * @credit: WooCommerce Cart Notices
		 *
		 * @since 1.0.0
		 *
		 * @return int|bool $minimum_amount free shipping minimum based on available zones
		 */
		private function get_cart_free_shipping_minimum() {
			$is_cart = ( is_callable( 'WC' ) && isset( WC()->cart ) && ! WC()->cart->is_empty() ) ? true : false;
			$minimum = false;
			// we only need this check if zones are available and the cart is shipped.
			// as a configured notice amount would have been check already when this is called.
			if ( ! $is_cart || ! WC()->cart->needs_shipping() ) {
				return $minimum;
			}

			$packages      = WC()->cart->get_shipping_packages();
			$free_minimums = array();

			// check all packages for available methods on each.
			foreach ( $packages as $i => $package ) {

				if ( empty( $package['contents'] ) ) {
					continue;
				}

				// hold the lowest free shipping minimum for this package.
				$free_minimums[ $i ] = '';

				$shipping = WC()->shipping()->load_shipping_methods( $package );

				// loop all package methods to get the min amount for any free shipping rate.
				// there could be more than one free shipping rate available.
				foreach ( $shipping as $method ) {

					// ensure we're looking at a free shipping rate assigned to a zone (instance ID can't be 0).
					if ( 'yes' === $method->enabled && 'free_shipping' === $method->id && $method->instance_id > 0 ) {

						// sanity check -- ensure that the min amount actually is in effect.
						if ( ! in_array( $method->requires, array( 'min_amount', 'either', 'both' ), true ) ) {
							continue;
						}

						// set the value for our first loop.
						// if we've already pushed a value, only push our new minimum if it's lower.
						if ( empty( $free_minimums[ $i ] ) ) {
							$free_minimums[ $i ] = $method->min_amount;
						} elseif ( $method->min_amount < $free_minimums[ $i ] ) {
							$free_minimums[ $i ] = $method->min_amount;
						}
					}
				}
			}

			// now we have the lowest min_amount for each package, pull the absolute lowest for the notice.
			$minimum = ! empty( $free_minimums ) ? (float) min( $free_minimums ) : false;

			return $minimum;
		}

	}
}

SA_Cart_Notices::get_instance();
