<?php
/**
 * Main class for Print Invoices
 *
 * @package     cashier/includes/
 *  author      StoreApps
 * @since       1.5.0
 * @version     1.1.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

if ( ! class_exists( 'SA_Print_Invoices' ) ) {

	/**
	 *  Print Invoices Class.
	 *
	 * @return object of SA_Print_Invoices having all functionality of Print Invoices
	 */
	class SA_Print_Invoices {

		/**
		 * Variable to hold instance of Print Invoices
		 *
		 * @var $instance
		 */
		private static $instance = null;

		/**
		 * Get single instance of Print Invoices.
		 *
		 * @return SA_Print_Invoices Singleton object of SA_Print_Invoices
		 */
		public static function get_instance() {
			// Check if instance is already exists.
			if ( is_null( self::$instance ) ) {
				self::$instance = new self();
			}

			return self::$instance;
		}

		/**
		 * Cloning is forbidden.
		 *
		 * @since 1.0.0
		 */
		private function __clone() {
			wc_doing_it_wrong( __FUNCTION__, __( 'Cheatin&#8217; huh?', 'cashier' ), '1.0.0' );
		}

		/**
		 * Unserializing instances of this class is forbidden.
		 *
		 * @since 1.0.0
		 */
		public function __wakeup() {
			wc_doing_it_wrong( __FUNCTION__, __( 'Cheatin&#8217; huh?', 'cashier' ), '1.0.0' );
		}

		/**
		 * Constructor
		 */
		private function __construct() {
			if ( ! defined( 'CFW_PRINT_INVOICES_DIRPATH' ) ) {
				define( 'CFW_PRINT_INVOICES_DIRPATH', dirname( __FILE__ ) );// phpcs:ignore
			}
			// add buttons for cashier actions for individual orders in Orders screen table.
			add_filter( 'woocommerce_admin_order_actions', array( $this, 'add_order_actions' ), 10, 2 );
			// add My Account actions.
			add_filter( 'woocommerce_my_account_my_orders_actions', array( $this, 'my_orders_actions' ), 10, 2 );
			// ajax to print invoice.
			add_action( 'wp_ajax_get_order_inv', array( $this, 'get_order_inv' ) );
			// add script and style.
			add_action( 'admin_footer', array( $this, 'styles_and_scripts' ) );
			add_action( 'wp_footer', array( $this, 'styles_and_scripts' ) );
		}

		/**
		 * Function to handle WC compatibility related function call from appropriate class
		 *
		 * @param string $function_name Function to call.
		 * @param array  $arguments Array of arguments passed while calling $function_name.
		 * @return mixed Result of function call.
		 */
		public function __call( $function_name, $arguments = array() ) {
			if ( ! is_callable( 'SA_WC_Compatibility_4_1', $function_name ) ) {
				return;
			}

			if ( ! empty( $arguments ) ) {
				return call_user_func_array( 'SA_WC_Compatibility_4_1::' . $function_name, $arguments );
			} else {
				return call_user_func( 'SA_WC_Compatibility_4_1::' . $function_name );
			}
		}

		/**
		 * Function to log messages generated by cart notices module
		 *
		 * @param  string $level   Message type. Valid values: debug, info, notice, warning, error, critical, alert, emergency.
		 * @param  string $message The message to log.
		 */
		public function log( $level = 'notice', $message = '' ) {
			if ( empty( $message ) ) {
				return;
			}

			if ( function_exists( 'wc_get_logger' ) ) {
				$logger  = wc_get_logger();
				$context = array( 'source' => 'cashier' );
				$logger->log( $level, $message, $context );
			} else {
				include_once plugin_dir_path( WC_PLUGIN_FILE ) . 'includes/class-wc-logger.php';
				$logger = new WC_Logger();
				$logger->add( 'cashier', $message );
			}
		}

		/**
		 * Function to fetch plugin's data
		 */
		public function get_plugin_data() {
			return get_plugin_data( SA_CFW_PLUGIN_FILE );
		}

		/**
		 * Adds order action icons to the Orders screen table for printing the invoice and packing list.
		 *
		 * Processed via Ajax.
		 *
		 * @internal
		 *
		 * @since 1.5.0
		 *
		 * @param array         $actions Order actions.
		 * @param int|\WC_Order $order Order object or order ID.
		 * @return array
		 */
		public function add_order_actions( $actions = array(), $order = null ) {

			if ( is_null( $order ) ) {
				return $actions;
			}

			if ( ! $order instanceof \WC_Order && is_numeric( $order ) ) {
				$wc_order = wc_get_order( $order );
			} else {
				$wc_order = $order;
			}

			if ( $wc_order instanceof \WC_Order && in_array( $wc_order->get_status(), $this->get_invoice_order_statuses( $wc_order ), true ) ) {

				$actions = array_merge(
					$actions,
					array(
						array(
							'name'   => __( 'Print Invoice', 'cashier' ),
							'action' => 'cfw_print_inv',
							'url'    => sprintf( '#%s', $wc_order->get_id() ),
						),
					)
				);
			}

			return $actions;
		}

		/**
		 * Adds an HTML invoice button to My Orders in My Account page so customers can view and print their invoices.
		 *
		 * @since 1.5.0
		 *
		 * @param array     $actions Associative array of actions.
		 * @param \WC_Order $order Order object.
		 * @return array Associative array of actions
		 */
		public function my_orders_actions( $actions = array(), $order = null ) {

			if ( is_null( $order ) ) {
				return $actions;
			}

			$user_can_view_inv = false;
			// this checks if a user is logged in.
			$user_id = get_current_user_id();

			// sanity check, returns false for customers not logged in.
			if ( 0 === (int) $user_id || ! is_numeric( $user_id ) ) {
				return $actions;
			}

			$user_can_view_inv = apply_filters( 'sa_cfw_user_can_view_inv', true, (int) $user_id );

			// this checks if is allowed to view invoices.
			if ( true !== $user_can_view_inv ) {
				return $actions;
			}

			if ( in_array( $order->get_status(), $this->get_invoice_order_statuses( $order ), true ) ) {
				$actions['sa_cfw_view_invoice'] = array(
					'url'  => sprintf( '#%s', $order->get_id() ),
					'name' => __( 'Print invoice', 'cashier' ),
				);
			}

			return $actions;
		}

		/**
		 * Gets an array of valid order statuses for displaying an invoice.
		 *
		 * @since 1.5.0
		 *
		 * @param \WC_Order|null $order optional order object passed in filter.
		 * @return string[]
		 */
		public function get_invoice_order_statuses( $order = null ) {

			/**
			 * Filters the order statuses valid to display an invoice to the customer on the My Account page.
			 *
			 * @since 1.5.0
			 *
			 * @param string[] $order_statuses array of allowed order statuses
			 * @param \WC_Order|null $order order object
			 */
			return apply_filters( 'sa_cfw_invoice_order_statuses', wc_get_is_paid_statuses(), $order );
		}

		/**
		 * Function to handle ajax action for print invoice
		 */
		public function get_order_inv() {
			check_ajax_referer( 'sa-cfw-print-inv', 'security' );
			$order_id = isset( $_POST['order_id'] ) ? absint( $_POST['order_id'] ) : 0;
			$order    = wc_get_order( $order_id );
			ob_start();
			$args = array(
				'order'    => $order,
				'order_id' => $order_id,
			);
			wc_get_template( 'cfw-print-invoice.php', $args, '', CFW_PRINT_INVOICES_DIRPATH . '/templates/' );
			wp_send_json_success( ob_get_clean() );
		}

		/**
		 * Function to add style and scripts
		 */
		public function styles_and_scripts() {
			global $post;
			$orders_endpoint = get_option( 'woocommerce_myaccount_orders_endpoint' );
			if ( ( ( ! empty( $post->post_type ) && 'shop_order' === $post->post_type ) ) || is_wc_endpoint_url( $orders_endpoint ) ) {
				?>
				<style type="text/css">
					.cfw_print_inv:after{
						font-family: dashicon;
						content: "\f193";
					}
				</style>
				<script type="text/javascript">
					jQuery(document).on( 'click', '.cfw_print_inv, .sa_cfw_view_invoice', function(){
						var order_id = parseInt((jQuery(this).attr('href')).replace( '#', ''));
						jQuery.ajax({
							type: 'POST',
							url: '<?php echo esc_url( admin_url( 'admin-ajax.php' ) ); ?>',
							dataType: 'json',
							data: { 
								'action': 'get_order_inv',
								'security' : '<?php echo esc_attr( wp_create_nonce( 'sa-cfw-print-inv' ) ); ?>',
								'order_id' : order_id
							},
							success: function( response ){
								let win = window.open('', 'Invoice');
								win.document.write(response.data);
								win.document.close();
								win.print();
							}
						});
					});
				</script>
				<?php
			}

		}

	}
}

SA_Print_Invoices::get_instance();
