<?php
/**
 * Uninstall file for the plugin. Runs when plugin is deleted in WordPress Admin.
 *
 * @package smoobu-calendar
 */

if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
	exit();
}

// Deletes the option generated by Settings API.
delete_option( 'smoobu_calendar_theme' );
delete_option( 'smoobu_full_width' );
delete_option( 'smoobu_custom_styling' );
delete_option( 'smoobu_custom_styling_border_shadow' );
delete_option( 'smoobu_custom_styling_border_radius' );
delete_option( 'smoobu_api_key' );
delete_option( 'smoobu_user_detail' );
delete_option( 'smoobu_properties_list' );

global $wpdb;
$table_name             = $wpdb->prefix . 'smoobu_calendar_availability';
$property_details_table = $wpdb->prefix . 'smoobu_property_details';
$wpdb->query( "DROP TABLE IF EXISTS {$table_name}" ); // phpcs:ignore
$wpdb->query( "DROP TABLE IF EXISTS {$property_details_table}" ); // phpcs:ignore
